/**
 * vite-env.d.ts
 *
 * Vite client type declarations — makes import.meta.env typed in TypeScript.
 *
 * Role in project:
 *   Build tooling types. Auto-generated by Vite. Do not modify manually.
 */
/// <reference types="vite/client" />
